version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            yarn add puppeteer
            yarn install

      - run:
          name: Deploy application
          command: yarn deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
